<?php
require_once __DIR__ . '/../verifica_sessao.php'; require_admin();
require_once __DIR__ . '/../pdo.php'; require_once __DIR__ . '/../utils.php';
require_once __DIR__ . '/../models/RelatorioFinanceiro.php';
$ano = $_GET['ano'] ?? date('Y'); if(!preg_match('/^\d{4}$/',$ano)) $ano=date('Y');
$diario=RelatorioFinanceiro::porPeriodo($pdo,$ano.'-01-01',$ano.'-12-31');
$meses=[]; for($m=1;$m<=12;$m++){$k=sprintf('%s-%02d',$ano,$m);$meses[$k]=['entradas'=>0,'saidas_caixa'=>0,'saidas_nao_caixa'=>0,'cartao'=>0,'total'=>0,'faturamento'=>0];}
foreach($diario as $data=>$l){$k=substr($data,0,7);foreach($meses[$k] as $c=>$v)$meses[$k][$c]+=(float)$l[$c];}
$totais=RelatorioFinanceiro::totais($meses);
$nomes=[1=>'Janeiro','Fevereiro','Marco','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
if(($_GET['export']??'')==='csv'){header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="financeiro-'.$ano.'.csv"');echo "\xEF\xBB\xBF";$o=fopen('php://output','w');fputcsv($o,['Mes','Entradas','Saidas caixa','Saidas nao caixa','Cartao','Total','Faturamento'],';','"','');foreach($meses as $k=>$l)fputcsv($o,[$nomes[(int)substr($k,5,2)],number_format($l['entradas'],2,',','.'),number_format($l['saidas_caixa'],2,',','.'),number_format($l['saidas_nao_caixa'],2,',','.'),number_format($l['cartao'],2,',','.'),number_format($l['total'],2,',','.'),number_format($l['faturamento'],2,',','.')],';','"','');fclose($o);exit;}
include __DIR__.'/layout.php';
?>
<style>.rf{max-width:1300px;margin:auto;display:grid;gap:18px}.rf-abas{display:flex;gap:8px;background:#fff;padding:8px;border-radius:12px;width:max-content}.rf-abas a,.rf-btn{padding:10px 15px;border-radius:8px;text-decoration:none;color:#5a371a;font-weight:bold}.rf-abas .ativa{background:#7b4f27;color:#fff}.rf-topo{display:flex;justify-content:space-between;align-items:end;gap:15px;flex-wrap:wrap}.rf-filtro{display:flex;gap:10px;align-items:end;background:#fff;padding:12px;border-radius:12px}.rf-filtro input{margin:5px 0 0}.rf-cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.rf-card,.rf-tabela{background:#fff;padding:17px;border-radius:13px;box-shadow:0 3px 10px #0001}.rf-card strong{display:block;font-size:23px;margin-top:6px}.rf-tabela{overflow:auto}.rf-tabela tr.total{font-weight:bold;background:#fff3df}</style>
<div class="rf"><nav class="rf-abas"><a href="financeiro.php">Diario</a><a href="financeiro_mensal.php?mes=<?=e($ano)?>-<?=date('m')?>">Mensal</a><a class="ativa" href="financeiro_anual.php?ano=<?=e($ano)?>">Anual</a></nav>
<div class="rf-topo"><div><h2>Relatorio anual</h2><p>Comparativo mensal de <?=e($ano)?>.</p></div><form class="rf-filtro"><div><label>Ano</label><input type="number" min="2000" max="2100" name="ano" value="<?=e($ano)?>"></div><button>Buscar</button><a class="rf-btn" href="?ano=<?=e($ano)?>&export=csv">Exportar CSV</a></form></div>
<div class="rf-cards"><?php foreach(['entradas'=>'Entradas','saidas_caixa'=>'Saidas caixa','saidas_nao_caixa'=>'Saidas nao caixa','cartao'=>'Total cartao','total'=>'Total','faturamento'=>'Faturamento anual'] as $c=>$r):?><div class="rf-card"><span><?=e($r)?></span><strong>R$ <?=number_format($totais[$c],2,',','.')?></strong></div><?php endforeach;?></div>
<div class="rf-tabela"><table><thead><tr><th>Mes</th><th>Entradas</th><th>Saidas caixa</th><th>Saidas nao caixa</th><th>Cartao</th><th>Total</th><th>Faturamento</th><th></th></tr></thead><tbody><?php foreach($meses as $k=>$l):?><tr><td><?=e($nomes[(int)substr($k,5,2)])?></td><td>R$ <?=number_format($l['entradas'],2,',','.')?></td><td>R$ <?=number_format($l['saidas_caixa'],2,',','.')?></td><td>R$ <?=number_format($l['saidas_nao_caixa'],2,',','.')?></td><td>R$ <?=number_format($l['cartao'],2,',','.')?></td><td>R$ <?=number_format($l['total'],2,',','.')?></td><td>R$ <?=number_format($l['faturamento'],2,',','.')?></td><td><a href="financeiro_mensal.php?mes=<?=e($k)?>">Ver dias</a></td></tr><?php endforeach;?><tr class="total"><td>Total do ano</td><?php foreach(['entradas','saidas_caixa','saidas_nao_caixa','cartao','total','faturamento'] as $c):?><td>R$ <?=number_format($totais[$c],2,',','.')?></td><?php endforeach;?><td></td></tr></tbody></table></div></div></div></div></div></body></html>
